// Code generated by protoc-gen-go.
// source: manage.proto
// DO NOT EDIT!

package Report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Command_CommandType int32

const (
	Command_CMT_INVALID Command_CommandType = 0
	// das<->tms
	Command_CMT_REQ_LOGIN Command_CommandType = 1
	Command_CMT_REP_LOGIN Command_CommandType = 32769
	// das<->tms
	Command_CMT_REQ_SETTING Command_CommandType = 16
	Command_CMT_REP_SETTING Command_CommandType = 32784
	// das->tss
	Command_CMT_REQ_HEART Command_CommandType = 6
	// das<->tms
	Command_CMT_REQ_PRICE Command_CommandType = 4
	Command_CMT_REP_PRICE Command_CommandType = 32772
	// das<->tms
	Command_CMT_REQ_MODE Command_CommandType = 3
	Command_CMT_REP_MODE Command_CommandType = 32771
	// das<->tms
	Command_CMT_REQ_MAX_CURRENT      Command_CommandType = 7
	Command_CMT_REP_MAX_CURRENT      Command_CommandType = 32775
	Command_CMT_REQ_CHARGING_PREPARE Command_CommandType = 32777
	Command_CMT_REP_CHARGING_PREPARE Command_CommandType = 9
	Command_CMT_REQ_CHARGING         Command_CommandType = 32778
	Command_CMT_REP_CHARGING         Command_CommandType = 10
	Command_CMT_REQ_STOP_CHARGING    Command_CommandType = 32782
	Command_CMT_REP_STOP_CHARGING    Command_CommandType = 14
)

var Command_CommandType_name = map[int32]string{
	0:     "CMT_INVALID",
	1:     "CMT_REQ_LOGIN",
	32769: "CMT_REP_LOGIN",
	16:    "CMT_REQ_SETTING",
	32784: "CMT_REP_SETTING",
	6:     "CMT_REQ_HEART",
	4:     "CMT_REQ_PRICE",
	32772: "CMT_REP_PRICE",
	3:     "CMT_REQ_MODE",
	32771: "CMT_REP_MODE",
	7:     "CMT_REQ_MAX_CURRENT",
	32775: "CMT_REP_MAX_CURRENT",
	32777: "CMT_REQ_CHARGING_PREPARE",
	9:     "CMT_REP_CHARGING_PREPARE",
	32778: "CMT_REQ_CHARGING",
	10:    "CMT_REP_CHARGING",
	32782: "CMT_REQ_STOP_CHARGING",
	14:    "CMT_REP_STOP_CHARGING",
}
var Command_CommandType_value = map[string]int32{
	"CMT_INVALID":              0,
	"CMT_REQ_LOGIN":            1,
	"CMT_REP_LOGIN":            32769,
	"CMT_REQ_SETTING":          16,
	"CMT_REP_SETTING":          32784,
	"CMT_REQ_HEART":            6,
	"CMT_REQ_PRICE":            4,
	"CMT_REP_PRICE":            32772,
	"CMT_REQ_MODE":             3,
	"CMT_REP_MODE":             32771,
	"CMT_REQ_MAX_CURRENT":      7,
	"CMT_REP_MAX_CURRENT":      32775,
	"CMT_REQ_CHARGING_PREPARE": 32777,
	"CMT_REP_CHARGING_PREPARE": 9,
	"CMT_REQ_CHARGING":         32778,
	"CMT_REP_CHARGING":         10,
	"CMT_REQ_STOP_CHARGING":    32782,
	"CMT_REP_STOP_CHARGING":    14,
}

func (x Command_CommandType) String() string {
	return proto.EnumName(Command_CommandType_name, int32(x))
}

type Command struct {
	Type         Command_CommandType `protobuf:"varint,1,opt,name=type,enum=Report.Command_CommandType" json:"type,omitempty"`
	Uuid         string              `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	Tid          uint64              `protobuf:"varint,3,opt,name=tid" json:"tid,omitempty"`
	SerialNumber uint32              `protobuf:"varint,4,opt,name=serial_number" json:"serial_number,omitempty"`
	Paras        []*Param            `protobuf:"bytes,5,rep,name=paras" json:"paras,omitempty"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}

func (m *Command) GetParas() []*Param {
	if m != nil {
		return m.Paras
	}
	return nil
}

func init() {
	proto.RegisterEnum("Report.Command_CommandType", Command_CommandType_name, Command_CommandType_value)
}
